name: iFlow
channels:
  - pytorch
  - conda-forge
dependencies:
  - pip=20.2.4
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - python=3.7.9
  - numpy==1.19.2
  - pytorch=1.6.0
  - scipy==1.5.3
  - matplotlib==3.3.2
  - pip:
    - tensorboardX>=1.8
    - jupyter==1.0.0
    - jupyter-console==6.2.0